import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CartBar from "./CartBar";
import Providers from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CartBar />
          <main className="mt-8">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
